"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['JLA-1.py']
DATA_FILES = ['Algebra_Stimuli.txt', 'mask1.jpg', 'mask2.jpg', 'mask3.jpg', 'mask4.jpg', 'ExperimentLibrary03.py', 'MyDots.py']
OPTIONS = {'argv_emulation': True,
           'packages' : ['wx', 'pygame']}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
